name: vaginal_genome_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake-minimal=7.32.4
  - trimmomatic=0.39
  - fastqc=0.12.1
  - kraken2=2.1.2
  - unicycler=0.5.0
  - checkm-genome=1.2.2
  - quast=5.2.0
